### PR TITLE
Added Missing Pokemon, Format and Spelling Fixes

### PR DESCRIPTION
**Pull request by GostOmega**
Added all the Missing Pokemon (involved in using a item to evolve).
Changed the format of:
`"type": "title",`
to:

```
"type": [
    "TITLE_1",
    "TITLE_2"
],
```

Fixed many MANY spelling mistakes from the previous version... if you find anymore I wouldn't be surprised lol.

### CODE REVIEW

**Comment by ed-george** [comment]
Thank you @GostOmega but this isn't currently valid JSON - Please can you fix the errors and then I will merge. Cheers.

**Comment by GostOmega** [comment]
There's only one small issue with this file:
From lines 2471 - 2475

```
"evolveChoice": [
      "Water Stone": "134",
      "Thunderstone": "135",
      "Fire Stone": "136"
    ],
```

Is it the proper format @ed-george ? It highlights the colons after each stone, should it be replaced with an equals sign? Other than this, the files is usable from my last commit [fa823c6](https://github.com/ed-george/KantoBOT/pull/4/commits/fa823c674d5a7e5be3d8aa3fe03a8de925a9cc0c)

**Comment by ed-george** [comment]
At a quick glance it is difficult to tell, please validate it with https://jsonformatter.curiousconcept.com

**Comment by GostOmega** [comment]
@ed-george All done, file is working 100% thanks for that website! Also if you haven't checked the Discord channel on what I posted, or if you haven't recently read up on the updates with Discord and Red Bot, been having conflicts with using the personal KantoBot cog inside Red, like it doesn't exist. I placed it in `Red-DiscordBot/cogs`, `Red-DiscordBot/data/downloader/cogs`, and `Red-DiscordBot/data/downloader/community/cogs` with all the necessary files, and attempted to "install" it through bot commands when active. Long story short, can't test KantoBot since I'm stumped and lack the knowledge on how their new cog system works.

**Pull request merged**
